### ISSUE TITLE
[ amazon-location-samples][maplibre-js-react-iot-asset-tracking] - Show map by local name

### ISSUE THREAD

**Issue by NguyenDOanNhan** [aws-samples/amazon-location-samples#105]
Thank you for updating the guide "maplibre-js-react-iot-asset-tracking", I appreciate your dedication.
I have a question is it currently only possible to display maps in English?
Can I show Amazon Location Services maps in Japanese?

**Comment by dreamorosi** [comment]
You're welcome, yes it is possible. I'll be adding a sample to show how to do it later today/tomorrow at the latest.

**Comment by NguyenDOanNhan** [comment]
OKi, 😊
Well, today, following the new instructions, I got some errors
1. You have written the default area code and account code, at step
"amplify the file /backend/awscloudformation/override.ts, we can use it to add policies to the IAM Amplify role. Open the file and replace it with the following:"
2. In step 8, your index.js file has root-CA.pem, but no instructions for renaming the file.
3. And finally some files were not found in the library at [node_modules]. Although I have tried adding files from amplify the source code. For example, an error line describes the following:
"Failed to parse source maps\maplibre-js-react-iot-asset-tracking\node_modules\maplibre-gl-js-amplify\src\utils.ts"

Please review the code, see if there is any part I forgot

**Comment by NguyenDOanNhan** [comment]
Also, I figured out how to display the language, it should look like this:

      const mbMap = new mapboxgl.Map ({
         container: "map",
         center: center, // original map center
         zoom: 10, // original map zoom
         style: mapName,
         change
       });
       mbMap.once('data type', function() {
         for (class mbMap.style.stylesheet.layers) {
           if (mbMap.style._serializedLayers [layer.id] .layout &&
              mbMap.style._serializedLayers [layer.id] .layout ['text-field'] &&
              mbMap.style._serializedLayers [layer.id] .layout ['text-field'] === '{_name_global}') {
             mbMap.setLayoutProperty(layer.id, 'text-field', '{_name_local}');
           }
         }
       });

Since I don't know much about React JS, mind you a bit

**Comment by dreamorosi** [comment]
> OKi, 😊 Today, following the new instructions, I got some errors
> 
> 1. You have written the default area code and account code, at step
>    "amplify the file /backend/awscloudformation/override.ts, we can use it to add policies to the IAM Amplify role. Open the file and replace it with the following:"

Good catch, I'll fix this in a future PR, thanks for noticing.

> 2. In step 8, your index.js file has root-CA.pem, but no instructions on how to rename the file.

The `root-CA.pem` file referenced in the script is the one you can download while creating your AWS IoT Thing in the console (see screenshot below):
<img width="590" alt="image" src="https://user-images.githubusercontent.com/7353869/153719304-b66f6caa-36e3-4ba2-b116-ad707fb01b72.png">

These same certificates are also available in the AWS IoT Core developer guide ([here](https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html#server-authentication-certs)), you can use the one that has "1" in the name.

> 3. And finally some files were not found in the library at [node_modules]. Although I have tried adding files from amplify the source code. For example, an error line describes the following:
>    "Failed to parse source maps\maplibre-js-react-iot-asset-tracking\node_modules\maplibre-gl-js-amplify\src\utils.ts"

These messages you see in the terminal when running the application are just warnings from webpack, the toll used to load & bundle packages. We are now using version `5.x` which generates some warnings on some of the modules imported. As long as the last message says something like `webpack 5.68.0 compiled with 13 warnings in 1243 ms` (version number, amount of warning and compile time might vary in your case) you can ignore them for the purpose of this sample.

Thanks a lot for all the feedback, I'll try to clarify the steps you pointed out even further so that other users will also benefit from this.

**Comment by dreamorosi** [comment]
This is how to generate a IoT Thing Policy
![Kapture 2022-02-12 at 18 05 56](https://user-images.githubusercontent.com/7353869/153721523-09177805-f531-418e-ac3c-d2ff9d6f0837.gif)

**Comment by dreamorosi** [comment]
This is how to create a IoT Thing, download the certificate, and rename them:
![Kapture 2022-02-12 at 18 22 43](https://user-images.githubusercontent.com/7353869/153721542-67d657d6-a002-4791-adba-98f52c83c8d7.gif)

**Comment by dreamorosi** [comment]
In a new PR I have clarified & updates the points you mentioned in one of the comment, I have also linked to the two videos above for future reference.

**Comment by dreamorosi** [comment]
I've added a new sample that shows how to interactively change the language of the map
![Kapture 2022-02-13 at 01 18 15](https://user-images.githubusercontent.com/7353869/153733699-c5ac8c98-7232-487c-8594-cd13a9090e67.gif)

**Comment by NguyenDOanNhan** [comment]
Thank you very much!
If something isn't right, I'll report the problem to you!
