### ISSUE TITLE
Can I use Amazon Location Service with MapBoxGL on React Native?

### ISSUE THREAD

**Issue by yudhiesh** [aws-samples/amazon-location-samples#8]
Would I be able to do so and should I use a specific version of [react-native-mapbox-gl/](https://github.com/react-native-mapbox-gl/maps)? 

In the [documentation](https://github.com/aws-samples/amazon-location-samples/tree/main/mapbox-gl-js-react) for the React example it mentions that:

> mapbox-gl@^2 and react-map-gl@^6 are NOT compatible with Amazon Location Service, as they require a Mapbox API key. This project pins these package versions to ^1.0.0 and ^5.0.0, respectively.

**Comment by mojodna** [comment]
Yes, you can use the [Mapbox Maps SDK for React Native](https://github.com/react-native-mapbox-gl/maps) with Amazon Location Service! The React Native bindings include bindings to Mapbox GL Native for iOS and Android. As of [8.1.0](https://github.com/react-native-mapbox-gl/maps/releases/tag/8.1.0), both dependencies are compatible (v5.9.0 for iOS, v9.1.0 for Android. However, you'll need to add support for [Signature Version 4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html), and we don't currently have any documentation on how to achieve this.

Because the underlying libraries differ between platforms, you'll need to implement platform-specific signing mechanisms, similar to what exist in the iOS and Android examples in this repository. For more information, check the [iOS](https://docs.aws.amazon.com/location/latest/developerguide/tutorial-mapbox-ios.html) and [Android](https://docs.aws.amazon.com/location/latest/developerguide/tutorial-mapbox-android.html) developer guides.

On Android, use `HttpRequestUtil` to update the `OkHttpClient` once the React context has been initialized:

```java
public class MainActivity extends ReactActivity {
    // ...

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        ReactInstanceManager im = getReactNativeHost().getReactInstanceManager();
        im.addReactInstanceEventListener(new ReactInstanceManager.ReactInstanceEventListener() {
            public void onReactContextInitialized(ReactContext validContext) {
                Mapbox.getTelemetry().disableTelemetrySession();

                // follow the developer guide for more information on wiring this up
                HttpRequestUtil.setOkHttpClient(
                    OkHttpClient.Builder()
                      .addInterceptor(new SigV4Interceptor(credentialProvider, SERVICE_NAME))
                      .build()
               )
            }
        });
```

On iOS, `MGLOfflineStorage` is a singleton object, so you don't need access to the underlying map view instance to wire up the delegate, which means that you can apply the applicable instructions from the [developer guide](https://docs.aws.amazon.com/location/latest/developerguide/tutorial-mapbox-ios.html) (translated to Obj-C) to `application:didFinishLaunchingWithOptions:` in `AppDelegate.m`.

**Comment by aarthigovardhanan88** [comment]
@yudhiesh, Did you succeeded in achieving this?
What version of react-native-mapbox-gl should be used?

Your help is much appreciated!

**Comment by vamshi9666** [comment]
@mojodna any example of this approach ?

**Comment by mojodna** [comment]
No, not yet. No one has tried this out yet; if you have a chance, I'd love to hear how it goes!
